Repository akka/akka-grpc, pull requests merged in 2020-08, with the labels that each got.

#1083 Update paradox akka to 0.35, new links to LB.com
  project/plugins.sbt
Labels: update

#1091 Update sbt-buildinfo to 0.10.0
  project/plugins.sbt
  project/project/buildinfo.sbt
Labels: update

#1071 Simple streaming handler benchmark
  benchmarks/README.md
  benchmarks/src/main/scala/akka/grpc/BenchRunner.scala
  benchmarks/src/main/scala/akka/grpc/CommonBenchmark.scala
  benchmarks/src/main/scala/akka/grpc/HandlerProcessingBenchmark.scala
  build.sbt
  project/plugins.sbt
Labels: update

#1086 Update compilerplugin, scalapb-runtime to 0.10.8
  project/plugins.sbt
Labels: update

#1093 Update scalatest to 3.1.3
  project/Dependencies.scala
Labels: update

#1082 Update grpc-core, grpc-interop-testing, ... to 1.31.0
  .travis.yml
  benchmark-java/build.sbt
  interop-tests/src/main/java/io/grpc/testing/integration2/ClientTester.java
  interop-tests/src/main/java/io/grpc/testing/integration2/GrpcJavaClientTester.java
  interop-tests/src/main/scala/io/grpc/testing/integration2/ChannelBuilder.scala
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  runtime/src/main/scala/akka/grpc/internal/NettyClientUtils.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1098 Website URL for the gradle plugin
  gradle-plugin/build.gradle
Labels: gradle

#1097 Update grpc-core, grpc-interop-testing, ... to 1.31.1
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1108 Adding grpc Scalapb option
  codegen/src/main/scala/akka/grpc/gen/ProtocSettings.scala
  codegen/src/main/scala/akka/grpc/gen/scaladsl/ScalaCodeGenerator.scala
Labels: codegen
