Repository akka/akka-grpc, pull requests merged in 2020-09, with the labels that each got.

#1110 Update sbt-jmh to 0.4.0
  project/plugins.sbt
Labels: update

#1112 Avoid some java/scaladoc errors in generated code
  codegen/src/main/twirl/templates/JavaServer/Handler.scala.txt
  codegen/src/main/twirl/templates/ScalaServer/Handler.scala.txt
  sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/build.sbt
  sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/test
  sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/test
Labels: codegen, sbt

#1116 Update sbt-mima-plugin to 0.8.0
  project/plugins.sbt
Labels: update

#1117 Update scalafmt-core to 2.7.0
  .scalafmt.conf
  build.sbt
  maven-plugin/src/main/scala/akka/grpc/maven/AbstractGenerateMojo.scala
  project/Common.scala
  project/CopyrightHeader.scala
  project/Dependencies.scala
  project/ReflectiveCodeGen.scala
  runtime/src/main/scala/akka/grpc/internal/ServerReflectionImpl.scala
  runtime/src/test/scala/akka/grpc/internal/MetadataImplSpec.scala
  sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala
Labels: update

#1119 Update grpc-core, grpc-interop-testing, ... to 1.32.1
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1120 Update org.eclipse.jgit to 5.9.0.202009080501-r
  project/plugins.sbt
Labels: update

#1102 Don't update beyond scalatest 3.1
  .scala-steward.conf
  project/Dependencies.scala
Labels: update

#1111 Don't cancel the incoming stream after reading the parameter
  interop-tests/src/test/scala/akka/grpc/scaladsl/GrpcMarshallingSpec.scala
  project/Dependencies.scala
  runtime/src/main/scala/akka/grpc/internal/SingleParameterSink.scala
  runtime/src/main/scala/akka/grpc/javadsl/GrpcMarshalling.scala
  runtime/src/main/scala/akka/grpc/scaladsl/GrpcMarshalling.scala
Labels: update

#1115 Expose helpers to bridge external generators to sbt
  project/ReflectiveCodeGen.scala
  sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala
  sbt-plugin/src/main/scala/akka/grpc/sbt/GeneratorBridge.scala
Labels: sbt
