Repository akka/akka-grpc, pull requests merged in 2020-04, with the labels that each got.

#897 Update akka-discovery, akka-slf4j, ... to 2.5.31
  project/Dependencies.scala
Labels: update

#895 Update sbt, scripted-plugin to 1.3.9
  benchmark-java/project/build.properties
  project/build.properties
Labels: update

#894 Update sbt-paradox-akka to 0.32
  project/plugins.sbt
Labels: update

#896 bump sbt-protoc & fix compatibility with other sbt-protoc plugins
  docs/src/main/paradox/buildtools/sbt.md
  project/plugins.sbt
  sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala
  sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/project/ProtocJSPlugin.scala
  sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/project/plugins.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/src/main/protobuf/helloworld.proto
  sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/src/test/protobuf/echo.proto
  sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/test
Labels: sbt, update

#900 Adapt public API's to accept either typed or classic systems
  codegen/src/main/twirl/templates/JavaServer/Handler.scala.txt
  codegen/src/main/twirl/templates/ScalaCommon/Marshallers.scala.txt
  codegen/src/main/twirl/templates/ScalaServer/Handler.scala.txt
  runtime/src/main/mima-filters/0.8.2.backwards.excludes/allow-either-classic-or-typed-actorsystem.backwards.excludes
  runtime/src/main/scala/akka/grpc/internal/GrpcEntityHelpers.scala
  runtime/src/main/scala/akka/grpc/internal/GrpcRequestHelpers.scala
  runtime/src/main/scala/akka/grpc/internal/GrpcResponseHelpers.scala
  runtime/src/main/scala/akka/grpc/javadsl/GrpcExceptionHandler.scala
  runtime/src/main/scala/akka/grpc/javadsl/GrpcMarshalling.scala
  runtime/src/main/scala/akka/grpc/javadsl/ServerReflection.scala
  runtime/src/main/scala/akka/grpc/javadsl/WebHandler.scala
  runtime/src/main/scala/akka/grpc/scaladsl/GrpcExceptionHandler.scala
  runtime/src/main/scala/akka/grpc/scaladsl/GrpcMarshalling.scala
  runtime/src/main/scala/akka/grpc/scaladsl/ServerReflection.scala
Labels: codegen

#902 Update sbt-publish-rsync to 0.2
  build.sbt
  project/plugins.sbt
Labels: update

#903 Update grpc-core, grpc-interop-testing, ... to 1.28.1
  benchmark-java/build.sbt
  gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: gradle, sbt, update

#904 Extract classic actor system via helper; improve generated API docs
  codegen/src/main/twirl/templates/JavaServer/Handler.scala.txt
  codegen/src/main/twirl/templates/JavaServer/PowerApiInterface.scala.txt
  codegen/src/main/twirl/templates/ScalaServer/Handler.scala.txt
  codegen/src/main/twirl/templates/ScalaServer/PowerApiTrait.scala.txt
  runtime/src/main/scala/akka/grpc/scaladsl/GrpcExceptionHandler.scala
Labels: codegen

#906 Adds a scripted tests which uses Akka 2.6.x
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-26/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-26/project/plugins.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-26/src/main/protobuf/helloworld.proto
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-26/src/main/scala/example/myapp/helloworld/GreeterServiceImpl.scala
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-26/test
Labels: sbt

#913 Update sbt-header to 5.5.0
  project/plugins.sbt
Labels: update

#916 Update sbt-scalafmt to 2.3.4
  project/plugins.sbt
Labels: update

#920 Update sbt, scripted-plugin to 1.3.10
  benchmark-java/project/build.properties
  project/build.properties
Labels: update

#923 Update sbt-header to 5.6.0
  project/plugins.sbt
Labels: update

#922 Update akka-http-cors to 0.4.3
  project/Dependencies.scala
Labels: update

#932 Remove unused import
  codegen/src/main/twirl/templates/JavaServer/Handler.scala.txt
Labels: codegen

#939 Update sbt-paradox-akka to 0.33
  project/plugins.sbt
Labels: update

#943 Avoid shipping classes already in scalapb-runtime
  runtime/src/main/mima-filters/0.8.4.backwards.excludes/dont-include-generated-google-protobuf-classes.backwards.excludes
  runtime/src/main/protobuf/google/protobuf/descriptor.proto
  sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/project/plugins.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/test
Labels: sbt
