Repository akka/akka-grpc, pull requests merged in 2021-05, with the labels that each got.

#1333 Fix client streaming cancellation before trailers read
  interop-tests/src/test/scala/akka/grpc/scaladsl/PowerApiSpec.scala
  runtime/src/main/scala/akka/grpc/internal/RequestBuilderImpl.scala
Labels: client

#1337 Update sbt-mima-plugin to 0.9.0
  project/plugins.sbt
Labels: update

#1338 Update protobuf-java to 3.16.0
  project/Dependencies.scala
Labels: update

#1339 Update sbt, scripted-plugin to 1.5.2
  benchmark-java/project/build.properties
  project/build.properties
  sbt-plugin/src/sbt-test/gen-java/02-server-reflection/project/build.properties
Labels: sbt, update

#1340 Update sbt-jmh to 0.4.1
  project/plugins.sbt
Labels: update

#1342 Update protobuf-java to 3.17.0
  project/Dependencies.scala
Labels: update

#1343 Update sbt-mima-plugin to 0.9.1
  project/plugins.sbt
Labels: update

#1341 Update sbt-jmh to 0.4.2
  project/plugins.sbt
Labels: update

#1346 Update compilerplugin, scalapb-runtime to 0.11.3
  project/plugins.sbt
Labels: update

#1345 Update org.eclipse.jgit to 5.11.1.202105131744-r
  project/plugins.sbt
Labels: update

#1344 Update grpc-core, grpc-interop-testing, ... to 1.37.1
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1336 Release directly to sonatype
  .github/workflows/build-test.yml
  .github/workflows/publish.yml
  .travis.yml
  build.sbt
  gradle-plugin/build.gradle
  project/Publish.scala
  project/plugins.sbt
Labels: gradle, update

#1351 Update sbt-protoc to 1.0.4
  project/plugins.sbt
Labels: update

#1355 No -SNAPSHOT postfix for gradle plugin snapshots
  .github/workflows/build-test.yml
  .travis.yml
  gradle-plugin/build.gradle
  gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy
Labels: gradle

#1356 Remove references to bintray
  .travis.yml
  RELEASING.md
  docs/release-train-issue-template-patch.md
  docs/release-train-issue-template.md
  gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy
  project/Common.scala
  project/project-info.conf
  sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/build.sbt
  sbt-plugin/src/sbt-test/gen-java/02-server-reflection/build.sbt
  sbt-plugin/src/sbt-test/gen-java/03-no-java-package/build.sbt
  sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-26/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/build.sbt
Labels: docs, gradle, sbt

#1357 Fix paradox tabs in client walkthrough
  docs/src/main/paradox/client/walkthrough.md
Labels: docs

#1352 Update grpc-core, grpc-interop-testing, ... to 1.38.0
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1359 Update protobuf-java to 3.17.1
  project/Dependencies.scala
Labels: update

#1360 Update sbt-mima-plugin to 0.9.2
  project/plugins.sbt
Labels: update

#1361 Update protobuf-java to 3.17.2
  project/Dependencies.scala
Labels: update
