Repository akka/akka-grpc, pull requests merged in 2021-07, with the labels that each got.

#1399 Update grpc-core, grpc-interop-testing, ... to 1.39.0
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1403 Fix incompatibilities when using Scala 2.13 artifacts with Scala 3
  codegen/src/main/twirl/templates/ScalaClient/Client.scala.txt
  sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala
Labels: codegen, sbt

#1404 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: update

#1405 Update sbt, scripted-plugin to 1.5.5
  benchmark-java/project/build.properties
  project/build.properties
  sbt-plugin/src/sbt-test/gen-java/02-server-reflection/project/build.properties
Labels: sbt, update

#1406 Add scala3 scripted test
  .github/workflows/build-test.yml
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/build.sbt
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/project/build.properties
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/project/plugins.sbt
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/src/main/protobuf/helloworld.proto
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/src/main/resources/application.conf
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/src/main/scala/example/myapp/helloworld/GreeterServiceImpl.scala
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/src/test/scala/example/myapp/helloworld/GreeterServiceSpec.scala
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/test
Labels: sbt

#1362 Update scala-library to 2.12.14
  .github/workflows/build-test.yml
  .travis.yml
  project/Common.scala
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/build.sbt
  sbt-plugin/src/sbt-test/gen-java/02-server-reflection/build.sbt
  sbt-plugin/src/sbt-test/gen-java/03-no-java-package/build.sbt
  sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-26/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/build.sbt
Labels: sbt, update

#1316 Fix product name in Contributing
  CONTRIBUTING.md
Labels: update

#1415 Update slf4j-api to 1.7.32
  project/Dependencies.scala
Labels: update

#1412 Update logback-classic to 1.2.4
  project/Dependencies.scala
Labels: update

#1418 Update paradox-theme-akka, ... to 0.39
  project/plugins.sbt
Labels: update

#1419 Update to akka-http 10.2.5
  project/Dependencies.scala
Labels: update
