Repository akka/akka-grpc, pull requests merged in 2021-11, with the labels that each got.

#1480 Update silencer-lib, silencer-plugin to 1.7.7
  project/Dependencies.scala
Labels: update

#1482 build: update to akka-http 10.2.7
  project/Dependencies.scala
Labels: update

#1479 build: update to Scala 2.13.7
  .github/workflows/build-test.yml
  project/Dependencies.scala
Labels: update

#1492 Update logback-classic to 1.2.7
  project/Dependencies.scala
Labels: update

#1483 Update grpc-core, grpc-interop-testing, ... to 1.42.0
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1490 Align protoc versions with protobuf
  build.sbt
  maven-plugin/src/main/maven/plugin.xml
  project/Dependencies.scala
  sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala
Labels: maven, sbt, update

#1476 Update sbt-unidoc to 0.5.0
  project/plugins.sbt
Labels: update

#1496 Validate Google Protobuf versions stay in sync
  .github/workflows/build-test.yml
  benchmark-java/build.sbt
  maven-plugin/src/main/maven/plugin.xml
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  project/GrpcVersionSyncCheckPlugin.scala
  project/VersionSyncCheckPlugin.scala
  sbt-plugin/src/main/scala/akka/grpc/sbt/AkkaGrpcPlugin.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: maven, sbt, update

#1473 Update sbt-ci-release to 1.5.10
  project/plugins.sbt
Labels: update

#1497 Update grpc-core, grpc-interop-testing, ... to 1.42.1
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1491 Fix error showing protoc logs
  gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy
Labels: gradle

#1498 Update sbt-scalafmt to 2.4.4
  project/plugins.sbt
Labels: update

#1477 Update protobuf-java to 3.19.1
  maven-plugin/src/main/maven/plugin.xml
  project/Dependencies.scala
Labels: maven, update

#1499 Update maven-core, maven-plugin-api to 3.8.4
  project/Dependencies.scala
Labels: update

#1502 Update paradox-theme-akka, ... to 0.40
  project/plugins.sbt
Labels: update
