Repository akka/akka-grpc, pull requests merged in 2021-08, with the labels that each got.

#1426 Update compilerplugin, scalapb-runtime to 0.11.5
  project/plugins.sbt
Labels: update

#1428 Update maven-core, maven-plugin-api to 3.8.2
  project/Dependencies.scala
Labels: update

#1416 Use `onlyIf` condition instead disable `javaCompile` task.
  gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPlugin.groovy
  gradle-plugin/src/test/groovy/unit/ApplySpec.groovy
Labels: gradle

#1435 Update sbt-mima-plugin to 1.0.0
  project/plugins.sbt
Labels: update

#1421 Update akka-http-cors to 1.1.2
  project/Dependencies.scala
Labels: update

#1438 Update sbt-reproducible-builds to 0.30
  project/plugins.sbt
Labels: update

#1439 Drop Whitesource
  .github/workflows/build-test.yml
  .github/workflows/publish.yml
  build.sbt
  docs/release-train-issue-template.md
  project/Whitesource.scala
  project/plugins.sbt
Labels: update

#1434 Update grpc-core, grpc-interop-testing, ... to 1.40.1
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1425 build: update to akka-http 10.2.6
  project/Dependencies.scala
Labels: update
