Repository akka/akka-grpc, pull requests merged in 2021-12, with the labels that each got.

#1513 Update sbt-protoc to 1.0.5
  project/plugins.sbt
Labels: update

#1515 Update to sbt 1.5.6
  project/build.properties
Labels: update

#1518 Update logback-classic to 1.2.8
  project/Dependencies.scala
Labels: update

#1520 Update sbt, scripted-plugin to 1.5.7
  project/build.properties
Labels: update

#1514 Update compilerplugin, scalapb-runtime to 0.11.7
  project/plugins.sbt
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/build.sbt
Labels: sbt, update

#1519 Update grpc-core, grpc-interop-testing, ... to 1.43.0
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1511 Adds service and method options
  codegen/src/main/scala/akka/grpc/gen/scaladsl/Method.scala
  codegen/src/main/scala/akka/grpc/gen/scaladsl/Service.scala
Labels: codegen

#1522 Update logback-classic to 1.2.9
  project/Dependencies.scala
Labels: update

#1523 sbt-paradox-akka: 0.40 -> 0.41
  project/plugins.sbt
Labels: update

#1524 Update grpc-core, grpc-interop-testing, ... to 1.43.1
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1525 Update sbt, scripted-plugin to 1.5.8
  project/build.properties
Labels: update

#1529 Update logback-classic to 1.2.10
  project/Dependencies.scala
Labels: update
