Repository akka/akka-grpc, pull requests merged in 2022-02, with the labels that each got.

#1564 Update sbt, scripted-plugin to 1.6.2
  project/build.properties
Labels: update

#1568 Update sbt-header to 5.6.5
  project/plugins.sbt
Labels: update

#1569 Update slf4j-api to 1.7.36
  project/Dependencies.scala
Labels: update

#1571 Update sbt-assembly to 1.1.1
  project/plugins.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/project/plugins.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-26/project/plugins.sbt
Labels: sbt, update

#1573 Update to Akka HTTP 10.2.8
  project/Dependencies.scala
Labels: update

#1576 Update protobuf-java to 3.19.4
  gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPluginExtension.groovy
  maven-plugin/src/main/maven/plugin.xml
  project/Dependencies.scala
  project/VersionSyncCheckPlugin.scala
Labels: maven, gradle, update

#1577 Update sbt-buildinfo to 0.11.0
  project/plugins.sbt
  project/project/buildinfo.sbt
Labels: update

#1581 Update compilerplugin, scalapb-runtime to 0.11.9
  project/plugins.sbt
Labels: update
