Repository akka/akka-grpc, pull requests merged in 2022-01, with the labels that each got.

#1535 Update sbt, scripted-plugin to 1.6.1
  project/build.properties
Labels: update

#1533 Update sbt-scalafmt to 2.4.6
  project/plugins.sbt
Labels: update

#1541 Update protobuf-java to 3.19.2
  maven-plugin/src/main/maven/plugin.xml
  project/Dependencies.scala
Labels: update

#1542 Update grpc-core, grpc-interop-testing, ... to 1.43.2
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update

#1543 Update sbt-protoc to 1.0.6
  project/plugins.sbt
Labels: update

#1545 Update compilerplugin, scalapb-runtime to 0.11.8
  project/plugins.sbt
Labels: update

#1539 Generated annotation
  codegen/src/main/twirl/templates/JavaClient/Client.scala.txt
  codegen/src/main/twirl/templates/JavaClient/ClientPowerApi.scala.txt
  codegen/src/main/twirl/templates/JavaCommon/ApiInterface.scala.txt
  codegen/src/main/twirl/templates/JavaServer/Handler.scala.txt
  codegen/src/main/twirl/templates/JavaServer/PowerApiInterface.scala.txt
  codegen/src/main/twirl/templates/ScalaClient/Client.scala.txt
  codegen/src/main/twirl/templates/ScalaCommon/ApiTrait.scala.txt
  codegen/src/main/twirl/templates/ScalaCommon/Marshallers.scala.txt
  codegen/src/main/twirl/templates/ScalaServer/Handler.scala.txt
  codegen/src/main/twirl/templates/ScalaServer/PowerApiTrait.scala.txt
  runtime/src/main/java/akka/grpc/AkkaGrpcGenerated.java
Labels: codegen

#1548 Replace silencer with nowarn
  codegen/src/main/scala/akka/grpc/gen/CodeGenerator.scala
  codegen/src/main/scala/akka/grpc/gen/javadsl/JavaCodeGenerator.scala
  codegen/src/main/scala/akka/grpc/gen/scaladsl/ScalaCodeGenerator.scala
  codegen/src/main/scala/akka/grpc/gen/scaladsl/ScalaMarshallersCodeGenerator.scala
  project/Common.scala
  project/Dependencies.scala
  runtime/src/main/scala/akka/grpc/internal/GrpcProtocolNative.scala
  runtime/src/main/scala/akka/grpc/internal/NettyClientUtils.scala
  runtime/src/main/scala/akka/grpc/internal/RequestBuilderImpl.scala
  runtime/src/main/scala/akka/grpc/javadsl/GrpcMarshalling.scala
  runtime/src/main/scala/akka/grpc/scaladsl/GrpcMarshalling.scala
Labels: codegen, update

#1549 Update scala-library to 2.13.8
  .github/workflows/build-test.yml
  project/Dependencies.scala
Labels: update

#1546 Update protobuf-java to 3.19.3
  maven-plugin/src/main/maven/plugin.xml
  project/Dependencies.scala
Labels: maven, update

#1451 Update scala-library to 2.12.15
  .github/workflows/build-test.yml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/build.sbt
  sbt-plugin/src/sbt-test/gen-java/02-server-reflection/build.sbt
  sbt-plugin/src/sbt-test/gen-java/03-no-java-package/build.sbt
  sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-26/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/build.sbt
  sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/build.sbt
Labels: sbt, update

#1557 Update slf4j-api to 1.7.34
  project/Dependencies.scala
Labels: update

#1559 Update grpc-core, grpc-interop-testing, ... to 1.44.0
  benchmark-java/build.sbt
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: sbt, update
