Repository akka/akka-grpc, pull requests merged in 2023-08, with the labels that each got.

#1822 chore: fix maven plugin for multi module build
  maven-plugin/src/main/scala/akka/grpc/maven/AbstractGenerateMojo.scala
Labels: maven

#1816 bump: proto-google-common-protos 2.22.1 (was 2.21.0)
  project/Dependencies.scala
Labels: update

#1820 bump: sbt, scripted-plugin 1.9.3 (was 1.9.1)
  benchmark-java/project/build.properties
  project/build.properties
Labels: update

#1817 bump: sbt-mima-plugin 1.1.3 (was 1.1.2)
  project/plugins.sbt
Labels: update

#1796 bump: Akka Cors 1.2.0
  project/Dependencies.scala
Labels: update

#1825 bump: proto-google-common-protos 2.23.0 (was 2.22.1)
  project/Dependencies.scala
Labels: update

#1826 bump: maven-core, maven-plugin-api 3.9.4 (was 3.9.3)
  project/Dependencies.scala
Labels: update

#1828 bump grpc from 1.54.1 to 1.54.2
  benchmark-java/build.sbt
  gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPluginExtension.groovy
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: gradle, sbt, update
