Repository akka/akka-grpc, pull requests merged in 2024-02, with the labels that each got.

#1896 build: Bump plugins to only fetch from maven central
  project/Common.scala
  project/plugins.sbt
Labels: update

#1903 bump: compilerplugin, scalapb-runtime 0.11.15 (was 0.11.14)
  project/plugins.sbt
Labels: update

#1901 bump: proto-google-common-protos 2.34.0 (was 2.30.0)
  project/Dependencies.scala
Labels: update

#1902 bump: sbt-protoc 1.0.7 (was 1.0.6)
  project/plugins.sbt
Labels: update

#1904 bump: grpc-core, grpc-interop-testing, ... 1.60.2 (was 1.60.0)
  benchmark-java/build.sbt
  gradle-plugin/src/main/groovy/akka/grpc/gradle/AkkaGrpcPluginExtension.groovy
  plugin-tester-java/pom.xml
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
Labels: gradle, sbt, update

#1851 fix: Fail queued requests on connection failure #1423
  interop-tests/src/test/scala/akka/grpc/scaladsl/AkkaHttpClientConnectionFailSpec.scala
  runtime/src/main/scala/akka/grpc/internal/AkkaHttpClientUtils.scala
  runtime/src/main/scala/akka/grpc/internal/SwitchOnCancel.scala
Labels: maven, gradle, update

#1886 feat: Periodic client discovery refresh #1152
  plugin-tester-java/build.gradle
  plugin-tester-java/pom.xml
  plugin-tester-scala/build.gradle
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  runtime/src/main/mima-filters/2.4.0.backwards.excludes/periodic-client-discovery.excludes
  runtime/src/main/resources/reference.conf
  runtime/src/main/scala/akka/grpc/GrpcClientSettings.scala
  runtime/src/main/scala/akka/grpc/internal/AkkaDiscoveryNameResolver.scala
  runtime/src/main/scala/akka/grpc/internal/AkkaDiscoveryNameResolverProvider.scala
  runtime/src/main/scala/akka/grpc/internal/ChannelUtils.scala
  runtime/src/main/scala/akka/grpc/internal/NettyClientUtils.scala
  runtime/src/test/scala/akka/grpc/internal/AkkaDiscoveryNameResolverProviderSpec.scala
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-27/build.sbt
Labels: sbt, update

#1905 feat: Native image metadata
  .github/workflows/native-image-tests.yml
  docs/src/main/paradox/deploy.md
  native-image-tests/README.md
  native-image-tests/grpc-scala/build.sbt
  native-image-tests/grpc-scala/project/build.properties
  native-image-tests/grpc-scala/project/plugins.sbt
  native-image-tests/grpc-scala/src/main/protobuf/helloworld.proto
  native-image-tests/grpc-scala/src/main/resources/META-INF/native-image/com.lightbend/grpc-scala/resource-config.json
  native-image-tests/grpc-scala/src/main/resources/application.conf
  native-image-tests/grpc-scala/src/main/resources/certs/ca.pem
  native-image-tests/grpc-scala/src/main/resources/certs/server1.key
  native-image-tests/grpc-scala/src/main/resources/certs/server1.pem
  native-image-tests/grpc-scala/src/main/resources/logback.xml
  native-image-tests/grpc-scala/src/main/scala/com/lightbend/helloworld/GreeterClient.scala
  native-image-tests/grpc-scala/src/main/scala/com/lightbend/helloworld/GreeterServer.scala
  native-image-tests/grpc-scala/src/main/scala/com/lightbend/helloworld/GreeterServiceImpl.scala
  native-image-tests/grpc-scala/src/main/scala/com/lightbend/helloworld/Main.scala
  plugin-tester-java/build.gradle
  plugin-tester-java/pom.xml
  plugin-tester-scala/build.gradle
  plugin-tester-scala/pom.xml
  project/Dependencies.scala
  project/VersionSyncCheckPlugin.scala
  runtime/src/main/resources/META-INF/native-image/io.grpc/grpc-netty/native-image.properties
  runtime/src/main/resources/META-INF/native-image/io.grpc/grpc-netty/reflect-config.json
  sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-akka-27/build.sbt
  sbt-plugin/src/sbt-test/scala-2_13/01-basic-client-server/build.sbt
  sbt-plugin/src/sbt-test/scala3/01-basic-client-server/build.sbt
Labels: sbt, update
